### ISSUE TITLE
How do you undo?

### ISSUE THREAD

**Issue by klische** [Devine-Davies/vs-make-hidden#10]
How do I undo a super hide?

**Comment by Devine-Davies** [comment]
Hello there & apologies for the late replay, when you say "undo a super hide"
1. Do you mean to make all files visible in the main directory again?
2. Or as in how CTRL+Z works?

If it's the 1st option then in the "Hidden In Directory" context pane looks for the item you wish to make visible and click on the arrow icon next to it. As for the second option, it's in the list of desired features & on the roadmap. As soon as there's an update on this I'll be to inform.

**Comment by klische** [comment]
Got it. Thanks!
