### ISSUE TITLE
Extension not working for the VSCode-Insiders releases.

### ISSUE THREAD

**Issue by richard-scott** [Devine-Davies/vs-make-hidden#11]
I'm using: 
```
Version: 1.32.0-insider (system setup)
Commit: 43228c493069ead7cfb7d57b2da1db20fc0acdaf
Date: 2019-03-06T01:28:07.880Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

And I can't get the extension to hide anything ;-(
I right click a file/folder, select 'hide', or 'show only', or 'super hide' and nothing happens.

In VS Code-1.31.1 I get a prompt for it to create '.vscode/settings.json and things get added to the exclude list.

It's just the Insiders version that this seems to have stopped working.

**Comment by initFabian** [comment]
Yep. This extension broke on v1.32.1 on mac

**Comment by Devine-Davies** [comment]
Hello and Thank you for bringing this to my attention, the issue should now be resolved. I have tested the plugin on both versions of vs code.
- Version 1.32.1 
- Version 1.33.0-insider

Update the plugin to the latest version of '2.3.5' and all should be in order. I'll keep this thread open for a little while just in case the problem persists.

Happy coding.

**Comment by richard-scott** [comment]
Well, it sort of works.... on opening a new empty folder and creating a new file. I then right click on the new file and choose hide and I get told this:

![image](https://user-images.githubusercontent.com/5149834/54200180-a68b4500-44c2-11e9-9a59-51d25093c2b9.png)

I then click on "Yes, Create file", and an empty ".vscode/settings.json" file is created with just "{}" in it and my file is still visible. I have to then right click and hide it again. Hides after that seem to work ok.

If I then delete the .vscode directory, any hidden files do not re-appear. I click on the filename in the "Hidden in Directory" Panel and I'm prompted to create the settings.json file again. 

When I do that, the file is created again, but it is empty. I can now see my hidden file, but the filename is still listed in the "Hidden in Directory" panel. However, this time I can click on it in the panel to remove it from that list of hidden items.
