### ISSUE TITLE
No longer works after updating VS Code

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [Devine-Davies/vs-make-hidden#18]
No longer works after update to:
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by Devine-Davies** [comment]
Hey ImanMahmoudinasab & thanks for the feedback.

I've tested the plugin on the latest version of VS Code witch I believe is Version: 1.44.2 on Mac OS. Are you able to provide me with further detail as to why it's not working for yourself so I can debug the issue further? 

- Which operating system you are using? 
- Are you using Workspaces?
- Is it a particular feature within the plugin that's not working correctly?

Again thank you for your time and happy to help :)

**Comment by ImanMahmoudinasab** [comment]
Hi Devine,
> Which operating system you are using?

Mac OS
>Are you using Workspaces?

I'm not sure I use :)

> Is it a particular feature within the plugin that's not working correctly?

None of options `Hide`, `Hide many`, ... works. When I click on these options nothing changes and I can see the file/folder I tried to hide.

Thank you for your support.

**Comment by Devine-Davies** [comment]
Hi and thanks for the quick response.

I forgot to mention can you check if you have a vs code settings.json file within the projects directory and that you have read and write permissions to that file. The plugin does prompt asking for permission to create one a settings.json file if one hasn't been detected. 

You can check the permissions of the file by right-clicking and selecting 'Get Info'. At the bottom of the Get Info window, you should be able to see who has read/write privileges.

Cheers.

![image](https://user-images.githubusercontent.com/4569419/80959951-c2a52080-8dff-11ea-87cc-46f8cd6ceb80.png)

**Comment by ImanMahmoudinasab** [comment]
> check if you have a vs code settings.json file within the projects directory and that you have read and write permissions to that file. 

![image](https://user-images.githubusercontent.com/5295554/80992423-5bcb3b80-8dee-11ea-92b4-478d546a4de2.png)

![image](https://user-images.githubusercontent.com/5295554/80992288-245c8f00-8dee-11ea-810c-a8ab86e59b12.png)

Cheers.

**Comment by Devine-Davies** [comment]
Is the plugin now working as expected?

**Comment by ImanMahmoudinasab** [comment]
Sorry, I forgot to mention the file already is there and has the permissions.
Is it possible the issue is a plugin conflict?
