### ISSUE TITLE
Hide by results in an error

### ISSUE THREAD

**Issue by reece** [Devine-Davies/vs-make-hidden#26]
Clicking "Hide by" in the explorer pane appears to do nothing.

If I use ctrl-shift-P, then type Hide by, I get this:

![image](https://user-images.githubusercontent.com/109453/161662276-688fd1b8-794a-43a3-a726-8b4a893213cc.png)

vs-make-hidden 4.0.4

vs code:
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic snap

**Comment by Devine-Davies** [comment]
Hey there Reece, cheers for commenting. Apologies for the late reply.

Yep, this is a known issue, when accessing the commands this way you have not selected a file/folder to hide. Therefore it fails as no arguments were provided. I agree this is not the best user experience and perhaps an alternative method could be used for selecting an item or to try and remove the commands from this menu.

Ill keep this in mind moving forward and try and work out a solution.

Happy coding.
