### ISSUE TITLE
Dosen't work in WSL2

### ISSUE THREAD

**Issue by KururiDao** [Devine-Davies/vs-make-hidden#28]
Version : 4.04
 in WSL2
Windows 10 Home

Thank you for the wonderful extension!

I see a field in Explorer, but when I run the command, it doesn't work at all.

Sorry to trouble you, but could you verify it?

**Comment by Devine-Davies** [comment]
Hi KururiDao

Thank you for your kind words and apologies for the late reply.

WSL2 is currently not supported but is on the road-map to be included. I'll be sure to post about this when supported.

Thanks again.
