### ISSUE TITLE
[bug] delete setting.json where file have parse error or comment

### ISSUE THREAD

**Issue by MarekLew** [Devine-Davies/vs-make-hidden#3]
the setting.json file should not be removed if it has an error in it (for example, a comment in a file).

Please copy the file or alert you to change but do not delete the contents.

This is fixed but not correct:
https://github.com/Devine-Davies/vs-make-hidden/issues/2

**Comment by Devine-Davies** [comment]
Thanks, @MarekLew for making me aware. I'll be sure to patch sometime this week and let you know when it has been amended. 👍
