### ISSUE TITLE
Workspaces are broken

### ISSUE THREAD

**Issue by rightaway** [Devine-Davies/vs-make-hidden#7]
I can create a workspace, but whether it's global or not, if I try to switch to it, it goes to a different one than the one I chose. Selecting workspaces doesn't seem to be working at all.

**Comment by Devine-Davies** [comment]
Hi Dev and thanks for the observation. 
I've added a fix in the last commit, so hopefully, this resolves the issue.

Cheers for the feedback, much appreciated.

**Comment by Devine-Davies** [comment]
Closing
